# Generated by Django 4.2.1 on 2023-06-01 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_details_subjects_marks'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Details',
            new_name='Detail',
        ),
        migrations.RenameModel(
            old_name='Marks',
            new_name='Mark',
        ),
        migrations.RenameModel(
            old_name='Subjects',
            new_name='Subject',
        ),
    ]
