# Generated by Django 4.2.1 on 2023-06-13 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_attendace'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attendace',
        ),
    ]
