# Generated by Django 4.2.1 on 2023-06-15 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_user_password1_user_password2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='password1',
        ),
        migrations.RemoveField(
            model_name='user',
            name='password2',
        ),
    ]
