# Generated by Django 4.2.1 on 2023-08-04 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_remove_user_password1_remove_user_password2'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='a3',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='a4',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='a5',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mark',
            name='m3',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mark',
            name='m4',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mark',
            name='m5',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='s3',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='s4',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='s5',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
