# Generated by Django 4.2.1 on 2023-08-08 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_attendance_a3_attendance_a4_attendance_a5_mark_m3_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('data', models.TextField(blank=True)),
            ],
        ),
    ]
