# Generated by Django 4.2.1 on 2023-08-09 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_user_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(default='static/images/2.webp', null=True, upload_to=''),
        ),
    ]
